### ISSUE TITLE
Need to refactor jenkins.slave

### ISSUE THREAD

**Issue by kshlm** [gluster/gluster.org_salt_states#1]
The jenkins.slave state right now includes configuration of the general GlusterFS regression testing environment, and the specific configuration for our community infrastructure. I want to breakout the general environment state into a seperate state. This will make it easier for other developers to contribute to improving the test environment, and make it easier to use the state to setup local testing environments.

**Comment by mscherer** [comment]
Any reason to not discuss that on the gluster infra list ?
Issue tracking is not made for discussion, and given github design, we can't delegate bug/issue triaging, so i was about to close it 5 minutes ago (not close this issue, close the whole issue tracking).

**Comment by kshlm** [comment]
I was just considering the salt-states as a project. I have no issue carrying forward the discussion on the mailing lists.

**Comment by mscherer** [comment]
i fear that if we start to discuss here, people will then start to send PR, and then as I would rather first use the ML for that than tying the whole infra to github. Ideally, moving to gerrit would be better, but only when we will have more than 1 single reviewer. So I am closing this ticket, and we will see on the infra list.
